providers:
  kubernetesIngress:
    enabled: true
  kubernetesGateway:
    enabled: true

gateway:
  enabled: true
  name: traefik-gateway
  listeners:
    web:
      port: 8000
      protocol: HTTP
      namespacePolicy:
        from: All

ingressRoute:
  dashboard:
    enabled: true

service:
  type: LoadBalancer