providers:
  kubernetesIngress:
    enabled: true
  kubernetesGateway:
    enabled: true
# Disable the Helm-provisioned Gateway to prevent conflicts
gateway:
  enabled: false

gatewayAPI:
  installCRDs: false

ingressRoute:
  dashboard:
    enabled: true

service:
  type: LoadBalancer