providers:
  kubernetesIngress:
    enabled: true
  kubernetesGateway:
    enabled: true

# Re-enable the official Gateway and allow cross-namespace routing
gateway:
  enabled: true

ingressRoute:
  dashboard:
    enabled: true

service:
  type: LoadBalancer