grafana:
  enabled: true
  adminPassword: "tass_admin" # Replace with a secure password or secret reference
  ingress:
    enabled: false # We use Gateway API HTTPRoute instead
  persistence:
    enabled: false
    # storageClassName: "strict-essd-pl0-me-central-1a" # Used our Alibaba CSI storage class
    # size: 10Gi

prometheus:
  prometheusSpec:
    retention: 7d
    storageSpec: {}
      # volumeClaimTemplate:
      #   spec:
      #     storageClassName: "strict-essd-pl0-me-central-1a"
      #     accessModes: ["ReadWriteOnce"]
      #     resources:
      #       requests:
      #         storage: 20Gi

# Enable default exporters for Kubernetes & RKE2
nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

alertmanager:
  config:
    global:
      resolve_timeout: 5m
      # Hostinger SMTP Settings
      smtp_smarthost: 'smtp.hostinger.com:587'
      smtp_from: 'tmizaoui@puffersoft.com'
      smtp_auth_username: 'tmizaoui@puffersoft.com'
      smtp_auth_password: 'willbeedited' # Use your actual Hostinger email password
      smtp_require_tls: true

    route:
      group_by: ['namespace', 'alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: 'email-notifications'
      routes:
        - receiver: 'email-notifications'
          matchers:
            - severity="warning"
        - receiver: 'email-notifications'
          matchers:
            - severity="critical"

    receivers:
    - name: 'email-notifications'
      email_configs:
      - to: 'tmizaoui@puffersoft.com' # The inbox where you want to receive the alerts
        send_resolved: true