apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaAlertRuleGroup
metadata:
  name: high-cpu-alert
  namespace: monitoring
spec:
  folder: "Operator Alerts"
  instanceSelector:
    matchLabels:
      dashboards: "kube-prometheus"
  interval: 1m
  rules:
    - name: "NodeCPUHigh"
      condition: "C"
      noDataState: "NoData"
      execErrState: "Error"
      data:
        - refId: "A"
          datasourceUid: "prometheus"
          model:
            datasource:
              type: "prometheus"
              uid: "prometheus"
            expr: '100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80'
            intervalMs: 1000
            maxDataPoints: 43200
            refId: "A"
        - refId: "C"
          datasourceUid: "__expr__"
          model:
            conditions:
              - evaluator:
                  params: [80]
                  type: "gt"
                operator:
                  type: "and"
                query:
                  params: ["A"]
                type: "query"
            datasource:
              name: "Expression"
              type: "__expr__"
              uid: "__expr__"
            expression: "A"
            refId: "C"
            type: "threshold"