apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-db-cluster
  namespace: default
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18
  primaryUpdateStrategy: unsupervised
  
  storage:
    size: 10Gi
    storageClass: strict-essd-pl0-me-central-1a
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi

  bootstrap:
    initdb:
      database: n8n
      owner: n8n