apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-app-cert
  namespace: traefik
spec:
  secretName: test-app-tls-secret
  issuerRef:
    name: letsencrypt-lab
    kind: ClusterIssuer
  dnsNames:
  - test-app-tasnim.awssolutionsprovider.com